language: python
sudo: false
cache: pip
dist: xenial
matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      sudo: true
install:
  - pip install tox-travis codecov
script:
  - tox -v
after_success:
  - codecov
notifications:
  email: false
